// Code generated from testdata/hw_driver_registry.json by
// scripts/gen_hw_registry.py; DO NOT EDIT by hand — regenerate instead.
//
// This is the Go equivalent of pwnagotchi/ui/hw/__init__.py's
// display_for() dispatch table: one entry per real hardware driver
// type string. Every entry except "dummydisplay" currently resolves to
// an unsupportedDriver (a real, typed "not implemented on this
// hardware/build yet" error on every operation) — see driver.go's
// package doc for why that's the honest status, not a placeholder.
package hw

// pythonClassNames maps each config alias to a driver's original
// Python class name, purely for diagnostic error text ("<ClassName>:
// this display driver has a real Go interface but no native
// implementation yet").
var pythonClassNames = map[string]string{
	"inky":                 "Inky",
	"whisplay":             "Whisplay",
	"inkyv2":               "InkyV2",
	"wavesharelcd0in96":    "Wavesharelcd0in96",
	"wavesharelcd1in3":     "Wavesharelcd1in3",
	"wavesharelcd1in8":     "Wavesharelcd1in8",
	"wavesharelcd1in9":     "Wavesharelcd1in9",
	"wavesharelcd1in14":    "Wavesharelcd1in14",
	"wavesharelcd1in28":    "Wavesharelcd1in28",
	"wavesharelcd1in47":    "Wavesharelcd1in47",
	"wavesharelcd1in54":    "Wavesharelcd1in54",
	"wavesharelcd1in69":    "Wavesharelcd1in69",
	"wavesharelcd2in0":     "Wavesharelcd2in0",
	"wavesharelcd2in4":     "Wavesharelcd2in4",
	"dummydisplay":         "DummyDisplay",
	"papirus":              "Papirus",
	"oledhat":              "OledHat",
	"lcdhat":               "LcdHat",
	"dfrobot_1":            "DFRobotV1",
	"dfrobot_2":            "DFRobotV2",
	"waveshare144lcd":      "Waveshare144lcd",
	"waveshare35lcd":       "Waveshare35lcd",
	"spotpear24inch":       "Spotpear24inch",
	"spotpear154lcd":       "Spotpear154lcd",
	"displayhatmini":       "DisplayHatMini",
	"pirateaudio":          "PirateAudio",
	"gfxhat":               "GfxHat",
	"argonpod":             "ArgonPod",
	"pitft":                "Pitft",
	"gamepi15":             "GamePi15",
	"gamepi20":             "GamePi20",
	"minipitft":            "MiniPitft",
	"minipitft2":           "MiniPitft2",
	"tftbonnet":            "TftBonnet",
	"waveshareoledlcd":     "Waveshareoledlcd",
	"waveshareoledlcdvert": "Waveshareoledlcdvert",
	"i2coled":              "I2COled",
	"waveshare1in02":       "Waveshare1in02",
	"waveshare1in54":       "Waveshare154",
	"waveshare1in54_v2":    "Waveshare154V2",
	"waveshare1in54b":      "Waveshare154inchb",
	"waveshare1in54b_v2":   "Waveshare154bV2",
	"waveshare1in54c":      "Waveshare1in54c",
	"waveshare1in64g":      "Waveshare1in64g",
	"waveshare2in7":        "Waveshare27inch",
	"waveshare2in7_v2":     "Waveshare27inchV2",
	"waveshare2in7b":       "Waveshare27b",
	"waveshare2in7b_v2":    "Waveshare27bV2",
	"waveshare2in9":        "Waveshare29inch",
	"waveshare2in9bc":      "Waveshare2in9bc",
	"waveshare2in9d":       "Waveshare2in9d",
	"waveshare2in9_v2":     "Waveshare29inchV2",
	"waveshare2in9b_v3":    "Waveshare29bV3",
	"waveshare2in9b_v4":    "Waveshare29bV4",
	"waveshare_1":          "WaveshareV1",
	"waveshare_2":          "WaveshareV2",
	"waveshare_3":          "WaveshareV3",
	"waveshare_4":          "WaveshareV4",
	"adafruit2in13_v3":     "Adafruit2in13V3",
	"waveshare2in13bc":     "Waveshare213bc",
	"waveshare2in13d":      "Waveshare213d",
	"waveshare2in13b_v3":   "Waveshare2in13bV3",
	"waveshare2in13b_v4":   "Waveshare213bV4",
	"waveshare2in13g":      "Waveshare2in13g",
	"waveshare2in36g":      "Waveshare2in36g",
	"waveshare2in66":       "Waveshare2in66",
	"waveshare2in66b":      "Waveshare2in66b",
	"waveshare2in66g":      "Waveshare2in66g",
	"waveshare3in0g":       "Waveshare3in0g",
	"waveshare3in7":        "Waveshare3in7",
	"waveshare3in52":       "Waveshare3in52",
	"waveshare4in01f":      "Waveshare4in01f",
	"waveshare4in2":        "Waveshare4in2",
	"waveshare4in2_v2":     "Waveshare4in2V2",
	"waveshare4in2b_v2":    "Waveshare4in2bV2",
	"waveshare4in2bc":      "Waveshare4in2bc",
	"waveshare4in26":       "Waveshare4in26",
	"waveshare4in37g":      "Waveshare4in37g",
	"waveshare5in65f":      "Waveshare5in65f",
	"waveshare5in79":       "Waveshare5in79",
	"waveshare5in79b":      "Waveshare5in79b",
	"waveshare5in83":       "Waveshare5in83",
	"waveshare5in83_v2":    "Waveshare5in83V2",
	"waveshare5in83b_v2":   "Waveshare5in83bV2",
	"waveshare5in83bc":     "Waveshare5in83bc",
	"waveshare7in3f":       "Waveshare7in3f",
	"waveshare7in3g":       "Waveshare7in3g",
	"waveshare7in5":        "Waveshare7in5",
	"waveshare7in5_HD":     "Waveshare7in5HD",
	"waveshare7in5_v2":     "Waveshare7in5V2",
	"waveshare7in5b_HD":    "Waveshare7in5bHD",
	"waveshare7in5b_v2":    "Waveshare7in5bV2",
	"waveshare7in5bc":      "Waveshare7in5bc",
	"waveshare13in3k":      "Waveshare13in3k",
}

// registeredTypes lists every display type string NewDriver accepts,
// in the same order as the original Python if/elif chain.
var registeredTypes = []string{
	"inky",
	"whisplay",
	"inkyv2",
	"wavesharelcd0in96",
	"wavesharelcd1in3",
	"wavesharelcd1in8",
	"wavesharelcd1in9",
	"wavesharelcd1in14",
	"wavesharelcd1in28",
	"wavesharelcd1in47",
	"wavesharelcd1in54",
	"wavesharelcd1in69",
	"wavesharelcd2in0",
	"wavesharelcd2in4",
	"dummydisplay",
	"papirus",
	"oledhat",
	"lcdhat",
	"dfrobot_1",
	"dfrobot_2",
	"waveshare144lcd",
	"waveshare35lcd",
	"spotpear24inch",
	"spotpear154lcd",
	"displayhatmini",
	"pirateaudio",
	"gfxhat",
	"argonpod",
	"pitft",
	"gamepi15",
	"gamepi20",
	"minipitft",
	"minipitft2",
	"tftbonnet",
	"waveshareoledlcd",
	"waveshareoledlcdvert",
	"i2coled",
	"waveshare1in02",
	"waveshare1in54",
	"waveshare1in54_v2",
	"waveshare1in54b",
	"waveshare1in54b_v2",
	"waveshare1in54c",
	"waveshare1in64g",
	"waveshare2in7",
	"waveshare2in7_v2",
	"waveshare2in7b",
	"waveshare2in7b_v2",
	"waveshare2in9",
	"waveshare2in9bc",
	"waveshare2in9d",
	"waveshare2in9_v2",
	"waveshare2in9b_v3",
	"waveshare2in9b_v4",
	"waveshare_1",
	"waveshare_2",
	"waveshare_3",
	"waveshare_4",
	"adafruit2in13_v3",
	"waveshare2in13bc",
	"waveshare2in13d",
	"waveshare2in13b_v3",
	"waveshare2in13b_v4",
	"waveshare2in13g",
	"waveshare2in36g",
	"waveshare2in66",
	"waveshare2in66b",
	"waveshare2in66g",
	"waveshare3in0g",
	"waveshare3in7",
	"waveshare3in52",
	"waveshare4in01f",
	"waveshare4in2",
	"waveshare4in2_v2",
	"waveshare4in2b_v2",
	"waveshare4in2bc",
	"waveshare4in26",
	"waveshare4in37g",
	"waveshare5in65f",
	"waveshare5in79",
	"waveshare5in79b",
	"waveshare5in83",
	"waveshare5in83_v2",
	"waveshare5in83b_v2",
	"waveshare5in83bc",
	"waveshare7in3f",
	"waveshare7in3g",
	"waveshare7in5",
	"waveshare7in5_HD",
	"waveshare7in5_v2",
	"waveshare7in5b_HD",
	"waveshare7in5b_v2",
	"waveshare7in5bc",
	"waveshare13in3k",
	"dummydisplay",
}
