// Code generated from testdata/display_type_alias_table.json by
// scripts/gen_display_table.py; DO NOT EDIT by hand — regenerate instead.
package config

// displayAliasEntry is one branch of utils.load_config's ~100-way
// if/elif chain that normalizes config['ui']['display']['type'].
type displayAliasEntry struct {
	// exactSet: true membership test (elif type in (a, b, c)).
	// false (substringOfLiteral): Python's real bug where a single-element
	// parenthesized string with no trailing comma, e.g. `in ('whisplay')`
	// written as `in 'whisplay'`, is a SUBSTRING test against that literal,
	// not a set-membership test. Preserved intentionally — see
	// docs/known-differences.md.
	exactSet         bool
	aliasesOrLiteral []string
	normalizedType   string
}

var displayAliasTable = []displayAliasEntry{
	{exactSet: true, aliasesOrLiteral: []string{"dummy", "dummydisplay"}, normalizedType: "dummydisplay"},
	{exactSet: false, aliasesOrLiteral: []string{"whisplay"}, normalizedType: "whisplay"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd0in96", "wslcd0in96"}, normalizedType: "wavesharelcd0in96"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in3", "wslcd1in3"}, normalizedType: "wavesharelcd1in3"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in8", "wslcd1in8"}, normalizedType: "wavesharelcd1in8"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in9", "wslcd1in9"}, normalizedType: "wavesharelcd1in9"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in14", "wslcd1in14"}, normalizedType: "wavesharelcd1in14"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in28", "wslcd1in28"}, normalizedType: "wavesharelcd1in28"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in47", "wslcd1in47"}, normalizedType: "wavesharelcd1in47"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in54", "wslcd1in54"}, normalizedType: "wavesharelcd1in54"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd1in69", "wslcd1in69"}, normalizedType: "wavesharelcd1in69"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd2in0", "wslcd2in0"}, normalizedType: "wavesharelcd2in0"},
	{exactSet: true, aliasesOrLiteral: []string{"wavesharelcd2in4", "wslcd2in4"}, normalizedType: "wavesharelcd2in4"},
	{exactSet: true, aliasesOrLiteral: []string{"inky", "inkyphat"}, normalizedType: "inky"},
	{exactSet: true, aliasesOrLiteral: []string{"inkyv2", "inkyphatv2"}, normalizedType: "inkyv2"},
	{exactSet: true, aliasesOrLiteral: []string{"papirus", "papi"}, normalizedType: "papirus"},
	{exactSet: false, aliasesOrLiteral: []string{"oledhat"}, normalizedType: "oledhat"},
	{exactSet: false, aliasesOrLiteral: []string{"lcdhat"}, normalizedType: "lcdhat"},
	{exactSet: true, aliasesOrLiteral: []string{"dfrobot_1", "df1"}, normalizedType: "dfrobot_1"},
	{exactSet: true, aliasesOrLiteral: []string{"dfrobot_2", "df2"}, normalizedType: "dfrobot_2"},
	{exactSet: true, aliasesOrLiteral: []string{"waveshare144lcd", "ws_144", "ws144", "waveshare_144", "waveshare144"}, normalizedType: "waveshare144lcd"},
	{exactSet: false, aliasesOrLiteral: []string{"spotpear24inch"}, normalizedType: "spotpear24inch"},
	{exactSet: false, aliasesOrLiteral: []string{"spotpear154lcd"}, normalizedType: "spotpear154lcd"},
	{exactSet: false, aliasesOrLiteral: []string{"displayhatmini"}, normalizedType: "displayhatmini"},
	{exactSet: false, aliasesOrLiteral: []string{"pirateaudio"}, normalizedType: "pirateaudio"},
	{exactSet: false, aliasesOrLiteral: []string{"gfxhat"}, normalizedType: "gfxhat"},
	{exactSet: false, aliasesOrLiteral: []string{"pitft"}, normalizedType: "pitft"},
	{exactSet: false, aliasesOrLiteral: []string{"argonpod"}, normalizedType: "argonpod"},
	{exactSet: false, aliasesOrLiteral: []string{"minipitft"}, normalizedType: "minipitft"},
	{exactSet: false, aliasesOrLiteral: []string{"minipitft2"}, normalizedType: "minipitft2"},
	{exactSet: false, aliasesOrLiteral: []string{"tftbonnet"}, normalizedType: "tftbonnet"},
	{exactSet: false, aliasesOrLiteral: []string{"waveshareoledlcd"}, normalizedType: "waveshareoledlcd"},
	{exactSet: false, aliasesOrLiteral: []string{"i2coled"}, normalizedType: "i2coled"},
	{exactSet: false, aliasesOrLiteral: []string{"waveshare35lcd"}, normalizedType: "waveshare35lcd"},
	{exactSet: false, aliasesOrLiteral: []string{"waveshareoledlcdvert"}, normalizedType: "waveshareoledlcdvert"},
	{exactSet: false, aliasesOrLiteral: []string{"gamepi20"}, normalizedType: "gamepi20"},
	{exactSet: false, aliasesOrLiteral: []string{"gamepi15"}, normalizedType: "gamepi15"},
	{exactSet: true, aliasesOrLiteral: []string{"adafruit2in13_v3", "adafruit2in13v3", "af213v3", "adafruit_213v3", "adafruit213inv3"}, normalizedType: "adafruit2in13_v3"},
	{exactSet: true, aliasesOrLiteral: []string{"waveshare1in02", "ws1in02", "ws102", "waveshare_102", "waveshare_1in02"}, normalizedType: "waveshare1in02"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_154inch", "waveshare1in54", "ws154inch", "waveshare_154", "waveshare154"}, normalizedType: "waveshare1in54"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_154inchb", "waveshare1in54b", "ws154inchb", "waveshare_154b", "waveshare154b"}, normalizedType: "waveshare1in54b"},
	{exactSet: true, aliasesOrLiteral: []string{"waveshare1in54c", "ws1in54c", "ws154c", "waveshare_154c", "waveshare_1in54c"}, normalizedType: "waveshare1in54c"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_154inchbv2", "waveshare1in54bv2", "waveshare1in54b_v2", "ws154inchbv2", "waveshare_154bv2", "waveshare154bv2"}, normalizedType: "waveshare1in54b_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_154inchv2", "waveshare1in54v2", "ws154inchv2", "waveshare_154inchv2", "waveshare154v2"}, normalizedType: "waveshare1in54_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"waveshare1in64g", "ws1in64g", "ws164g", "waveshare_164g", "waveshare_1in64g"}, normalizedType: "waveshare1in64g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_1", "ws1", "waveshare_1", "waveshare1", "waveshare2in13"}, normalizedType: "waveshare_1"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2", "ws2", "waveshare_2", "waveshare2", "waveshare2in13v2"}, normalizedType: "waveshare_2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_3", "ws3", "waveshare_3", "waveshare3", "waveshare2in13v3"}, normalizedType: "waveshare_3"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4", "ws4", "waveshare_4", "waveshare4", "waveshare2in13v4"}, normalizedType: "waveshare_4"},
	{exactSet: true, aliasesOrLiteral: []string{"waveshare2in13b_v3", "waveshare2in13b_v3", "ws213bv3", "waveshare_213bv3", "waveshare213inb_v3"}, normalizedType: "waveshare2in13b_v3"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_213bv4", "waveshare2in13b_v4", "ws213bv4", "waveshare_213bv4", "waveshare213inb_v4"}, normalizedType: "waveshare2in13b_v4"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_213bc", "ws213bc", "waveshare2in13bc", "waveshare_213bc", "waveshare213bc"}, normalizedType: "waveshare2in13bc"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_213d", "ws213d", "waveshare2in13d", "waveshare_213d", "waveshare213d"}, normalizedType: "waveshare2in13d"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_213g", "waveshare2in13g", "waveshare213g", "ws213g", "waveshare_213g"}, normalizedType: "waveshare2in13g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in36g", "waveshare2in36g", "waveshare236g", "ws236g", "waveshare_236g"}, normalizedType: "waveshare2in36g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in66", "waveshare2in66", "waveshare266", "ws266", "waveshare_266"}, normalizedType: "waveshare2in66"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in66b", "waveshare2in66b", "waveshare266b", "ws266b", "waveshare_266b"}, normalizedType: "waveshare2in66b"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in66g", "waveshare2in66g", "waveshare266g", "ws266g", "waveshare_266g"}, normalizedType: "waveshare2in66g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_27inch", "ws27inch", "waveshare2in7", "waveshare_27inch", "waveshare27"}, normalizedType: "waveshare2in7"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in7v2", "waveshare2in7_v2", "waveshare2in7v2", "ws27inchv2", "waveshare_27v2", "waveshare27v2"}, normalizedType: "waveshare2in7_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in7bv2", "waveshare2in7b_v2", "waveshare2in7bv2", "ws27inchbv2", "waveshare_27bv2", "waveshare27bv2"}, normalizedType: "waveshare2in7b_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in9", "waveshare2in9", "ws29inch", "waveshare_29inch", "waveshare29inch"}, normalizedType: "waveshare2in9"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in9bc", "waveshare2in9bc", "ws2in9bc", "ws29bc", "waveshare_29bc", "waveshare_2in9bc"}, normalizedType: "waveshare2in9bc"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in9d", "waveshare2in9d", "ws2in9d", "ws29d", "waveshare_29d", "waveshare_2in9d"}, normalizedType: "waveshare2in9d"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in9v2", "waveshare2in9_v2", "waveshare2in9v2", "ws2in9v2", "waveshare_29v2", "waveshare29v2"}, normalizedType: "waveshare2in9_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in9bv3", "waveshare2in9b_v3", "waveshare2in9bv3", "ws2in9bv3", "waveshare_29bv3", "waveshare29bv3"}, normalizedType: "waveshare2in9b_v3"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_2in9bv4", "waveshare2in9b_v4", "waveshare2in9bv4", "ws2in9bv4", "waveshare_29bv4", "waveshare29bv4"}, normalizedType: "waveshare2in9b_v4"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_3in0g", "waveshare3in0g", "ws3in0g", "waveshare_30g", "waveshare30g"}, normalizedType: "waveshare3in0g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_3in7", "waveshare3in7", "ws3in7", "waveshare_37", "waveshare37"}, normalizedType: "waveshare3in7"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_3in52", "waveshare3in52", "ws3in52", "waveshare_352", "waveshare352"}, normalizedType: "waveshare3in52"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in01f", "waveshare4in01f", "ws4in01f", "waveshare_401f", "waveshare401f"}, normalizedType: "waveshare4in01f"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in2", "waveshare4in2", "ws4in2", "waveshare_42", "waveshare42"}, normalizedType: "waveshare4in2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in2v2", "waveshare4in2v2", "ws4in2v2", "waveshare_42v2", "waveshare42v2"}, normalizedType: "waveshare4in2_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in2bv2", "waveshare4in2bv2", "ws4in2bv2", "waveshare_42bv2", "waveshare42bv2"}, normalizedType: "waveshare4in2b_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in2bc", "waveshare4in2bc", "ws4in2bc", "waveshare_42bc", "waveshare42bc"}, normalizedType: "waveshare4in2bc"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in26", "waveshare4in26", "ws4in26", "waveshare_426", "waveshare426"}, normalizedType: "waveshare4in26"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_4in37g", "waveshare4in37g", "ws4in37g", "waveshare_37g", "waveshare437g"}, normalizedType: "waveshare4in37g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in65f", "waveshare5in65f", "ws5in65f", "waveshare_565f", "waveshare565f"}, normalizedType: "waveshare5in65f"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in79", "waveshare5in79", "ws5in79", "waveshare_579", "waveshare579"}, normalizedType: "waveshare5in79"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in79b", "waveshare5in79b", "ws5in79b", "waveshare_579b", "waveshare579b"}, normalizedType: "waveshare5in79b"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in83", "waveshare5in83", "ws5in83", "waveshare_583", "waveshare583"}, normalizedType: "waveshare5in83"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in83v2", "waveshare5in83v2", "ws5in83v2", "waveshare_583v2", "waveshare583v2"}, normalizedType: "waveshare5in83_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in83bv2", "waveshare5in83bv2", "ws5in83bv2", "waveshare_583bv2", "waveshare583bv2"}, normalizedType: "waveshare5in83b_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_5in83bc", "waveshare5in83bc", "ws5in83bc", "waveshare_583bc", "waveshare583bc"}, normalizedType: "waveshare5in83bc"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in3f", "waveshare7in3f", "ws7in3f", "waveshare_73f", "waveshare73f"}, normalizedType: "waveshare7in3f"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in3g", "waveshare7in3g", "ws7in3g", "waveshare_73g", "waveshare73g"}, normalizedType: "waveshare7in3g"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in5", "waveshare7in5", "ws7in5", "waveshare_75", "waveshare75"}, normalizedType: "waveshare7in5"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in5hd", "waveshare7in5hd", "ws7in5hd", "waveshare_75hd", "waveshare75hd"}, normalizedType: "waveshare7in5_HD"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in5v2", "waveshare7in5v2", "ws7in5v2", "waveshare_75v2", "waveshare75v2"}, normalizedType: "waveshare7in5_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in5bhd", "waveshare7in5bhd", "ws7in5bhd", "waveshare_75bhd", "waveshare75bhd"}, normalizedType: "waveshare7in5b_HD"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in5bv2", "waveshare7in5bv2", "ws7in5bv2", "waveshare_75bv2", "waveshare75bv2"}, normalizedType: "waveshare7in5b_v2"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_7in5bc", "waveshare7in5bc", "ws7in5bc", "waveshare_75bc", "waveshare75bc"}, normalizedType: "waveshare7in5bc"},
	{exactSet: true, aliasesOrLiteral: []string{"ws_13in3k", "waveshare13in3k", "ws13in3k", "waveshare_133k", "waveshare133k"}, normalizedType: "waveshare13in3k"},
	{exactSet: true, aliasesOrLiteral: []string{"weact2in9", "weact29in"}, normalizedType: "weact2in9"},
}
